


name: CI for Stagging

on:
  push:
    branches:
      - stagging

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Deploy to Staging Server
        run: |
          ssh user@staging-server "cd /path/to/app && git pull origin stagging && npm install && pm2 restart all"
