name: Test CI/CD

on:
  push:
    branches:
      - "bugfix/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Test
        run: echo "Hello World"
