name: CI for Dev and Feature

on:
  push:
    branches:
      - dev
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run CI
        run: echo "CI/CD pipeline triggered for branch ${{ github.ref_name }}"
